pickle_dir: '../../data/preprocess/classic_piano'
epochs: 1000
batch_size: 8
load_path:
dropout: 0.1
debug: 'true'
l_r: 0.001
label_smooth: 0.1
event_dim: 388 
embedding_dim: 512
num_layers: 6
max_seq: 1024
experiment: 'yuval512-layer6'

